title: Evgenii Venkov # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A senior year bachelor student in Information and Communication Technology, passionate about
  programming, music and sports. Has extensive and
  broad knowledge in many different areas. Reliable team member with previous working
  experience in the industry that is always striving to learn more.
  <br><br>
  <br><br>
  <a href="https://orievg.github.io">My website</a>
  <br><br>
  <a href="https://orievg.github.io/pdf/CV.pdf">My CV</a>
  
theme: jekyll-theme-minimal
